sudo: required

services:
  - docker

language: node_js
node_js:
  - "6.1"

after_success:
  - "docker build -t anon-chat ."
  - "docker run --name some-mongo -d mongo"
  - "docker run -p 8080:8080 --link some-mongo:mongo -d anon-chat"
